### ISSUE TITLE
Dev todo #1

### ISSUE THREAD

**Issue by electrovoyage** [TPEcool/Game-Idea-Generator#1]
- [x] Clear saves
- [x] Autogenerate
- [x] Side genre system with dupe checker and additional options
- [x] Several rolls
- [x] Audio feedback
- [x] ~~Add more save slots~~ - not happening, will exceed Scratch's limit of ten cloud variables
- [x] Add name generator module, perhaps via lists?
- [x] ~~Make more variations possible, via lists~~ - not happening either, due to the name generator complicating this
- [ ] Change background, desirably a moving grid
- [ ] UI redesign
